name: Generate Pacman

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"

permissions:
  contents: write

jobs:
  generate:
    runs-on: ubuntu-latest

    steps:
      # ðŸ”¹ obrigatÃ³rio
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Generate pacman contribution graph
        uses: abozanona/pacman-contribution-graph@main
        with:
          github_user_name: CaioColli

      # ðŸ”¹ publica os SVGs corretos
      - name: Push pacman to output branch
        uses: crazy-max/ghaction-github-pages@v4
        with:
          target_branch: output_
